[package]
name = "oxide_eval"
version = "0.1.0"
edition = "2021"

[dependencies]
oxc = "^0.66.0"
serde_json = "~1"
anyhow = "~1.0.98"

[dependencies.regex]
version = "~1"
optional = true

[features]
string = ["regex"]
array = []
math = []